const getRowsSummary = (summary = {}) => [
  ["Jumlah Total Hari Kerja", summary.jlh_hari_kerja || 0],
  ["Alpha", summary.alfa || 0],
  ["Sakit", summary.sakit || 0],
  ["Tidak Upacara Hari Besar", 0],
  ["Tidak Apel Pagi/Sore", 0],
  ["Izin", summary.izin || 0],
  ["Cuti", summary.cuti || 0],
  ["Tugas Luar", summary.tugas_luar || 0],
  ["Tidak Absen Pulang", summary.tidak_absen_sore || 0],
  ["Cuti Melahirkan", 0],
  ["Cuti Melahirkan > 3", 0],
  ["Bekerja Dari Rumah", 0],
  ["Cuti Tahunan", 0],
  ["Hadir", summary.hadir || 0],
  ["Terlambat Masuk 1 - 30 Menit", summary.tmk1 || 0],
  ["Terlambat Masuk 31 - 60 Menit", summary.tmk2 || 0],
  ["Terlambat Masuk 61 - 90 Menit", summary.tmk3 || 0],
  ["Terlambat Masuk > 91 Menit", summary.tmk4 || 0],
  ["Pulang Lebih Awal 1 - 30 Menit", summary.psw1 || 0],
  ["Pulang Lebih Awal 31 - 60 Menit", summary.psw2 || 0],
  ["Pulang Lebih Awal 61 - 90 Menit", summary.psw3 || 0],
  ["Pulang Lebih Awal > 91 Menit", summary.psw4 || 0],
  ["Cuti Sakit", 0],
  ["Akumulasi Izin + Sakit ( max 3 Hari )", 0],
  ["Absen Dibatalkan", 0],
  ["Hasil Investigasi", 0],
  ["Absen Masuk Dibatalkan", 0],
  ["Absen Keluar Dibatalkan", 0],
];

export default getRowsSummary;